env:
    OEM: realme
    CODENAME: RMX1901
    CIRRUS_CI: true
    CIRRUS_SHELL: bash
    TARGET: m bacon -j16
    ROM_NAME: octavi
    PRODUCT_NAME: octavi_RMX1901
    VARIANT: userdebug
    ROM_REPO: "https://github.com/Octavi-Staging/android_manifest.git"
    ROM_BRANCH: thirteen
    DEVICE_REPO: "https://github.com/shravansayz/device_realme_RMX1901"
    DEVICE_BRANCH: octavi
    VENDOR_REPO: "https://github.com/SlicKker-001/device_realme_RMX1901"
    VENDOR_BRANCH: 13
    KERNEL_REPO: "https://github.com/ashim-anwar/kernel_realme_RMX1901"
    KERNEL_BRANCH: x.337-KSU
    USERNAME: sksayz5
    USERMAIL: sksayz5@gmail.com
    OUTPUT: OctaviOS*.zip
    
task:
  name: "ROM Build"
  timeout_in: 240m
  trigger_type: manual
  container:
      image: ghcr.io/satorugojo2k23/ubuntu:latest
      cpu: 8
      memory: 32G

# CLONE_SCRIPT_script: |
 #   if [ -z "$CIRRUS_PR" ]; then
 #     git clone --recursive --branch=$CIRRUS_BRANCH https://x-access-token:${CIRRUS_REPO_CLONE_TOKEN}@github.com/${CIRRUS_REPO_FULL_NAME}.git $CIRRUS_WORKING_DIR
  #    git reset --hard $CIRRUS_CHANGE_IN_REPO
  #  else
  #    git clone --recursive https://x-access-token:${CIRRUS_REPO_CLONE_TOKEN}@github.com/${CIRRUS_REPO_FULL_NAME}.git $CIRRUS_WORKING_DIR
  #    git fetch origin pull/$CIRRUS_PR/head:pull/$CIRRUS_PR
   #   git reset --hard $CIRRUS_CHANGE_IN_REPO
  #  fi    

  SYNC_SCRIPT_script:
      - curl -sL https://raw.githubusercontent.com/sksayz5/ROM-Builder-CI/main/scripts/build_rom.sh | bash
      
  BUILD_SCRIPT_script:
      - curl -sL https://raw.githubusercontent.com/sksayz5/ROMBuilder-CI/main/scripts/build_rom.sh | bash
      
  UPLOAD_SCRIPT_script:
      - curl -sL https://raw.githubusercontent.com/sksayz5/ROMBuilder-CI/main/scripts/upload_rom.sh | bash
