env:
    OEM: realme
    CODENAME: RMX2020
    CIRRUS_CI: true
    CIRRUS_SHELL: bash
    TARGET: m bacon -j16
    ROM_NAME: lineage
    PRODUCT_NAME: lineage_RMX2020
    VARIANT: userdebug
    ROM_REPO: "https://github.com/crdroidandroid/android.git"
    ROM_BRANCH: 13.0 --git-lfs
    DEVICE_REPO: "https://github.com/SatoruGojo2k23/device_realme_RMX2020"
    DEVICE_BRANCH: crdroid-13.0
    VENDOR_REPO: "https://github.com/ArrowOS-Devices/android_vendor_realme_RMX2020"
    VENDOR_BRANCH: arrow-13.0
    KERNEL_REPO: "https://github.com/ArrowOS-Devices/android_kernel_realme_RMX2020"
    KERNEL_BRANCH: arrow-13.0
    USERNAME: satorugojo2k23
    USERMAIL: satorugojo4200@gmail.com
    OUTPUT: crDroid*.zip
    
task:
  name: "ROM Build"
  timeout_in: 240m
  trigger_type: manual
  container:
      image: ghcr.io/satorugojo2k23/ubuntu:latest
      cpu: 8
      memory: 32G

# CLONE_SCRIPT_script: |
 #   if [ -z "$CIRRUS_PR" ]; then
 #     git clone --recursive --branch=$CIRRUS_BRANCH https://x-access-token:${CIRRUS_REPO_CLONE_TOKEN}@github.com/${CIRRUS_REPO_FULL_NAME}.git $CIRRUS_WORKING_DIR
  #    git reset --hard $CIRRUS_CHANGE_IN_REPO
  #  else
  #    git clone --recursive https://x-access-token:${CIRRUS_REPO_CLONE_TOKEN}@github.com/${CIRRUS_REPO_FULL_NAME}.git $CIRRUS_WORKING_DIR
  #    git fetch origin pull/$CIRRUS_PR/head:pull/$CIRRUS_PR
   #   git reset --hard $CIRRUS_CHANGE_IN_REPO
  #  fi    

  SYNC_SCRIPT_script:
      - curl -sL https://raw.githubusercontent.com/SatoruGojo2k23/ROMBuilder-CI/crdroid-13.0/scripts/sync_rom.sh | bash
      
  BUILD_SCRIPT_script:
      - curl -sL https://raw.githubusercontent.com/SatoruGojo2k23/ROMBuilder-CI/crdroid-13.0/scripts/build_rom.sh | bash
      
  UPLOAD_SCRIPT_script:
      - curl -sL https://raw.githubusercontent.com/SatoruGojo2k23/ROMBuilder-CI/crdroid-13.0/scripts/upload_rom.sh | bash
